name: format_then_lint_code

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}
          fetch-depth: 0
          persist-credentials: true  # Allow pushing changes back

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      - name: Run isort (sort imports with black profile)
        run: |
          isort . --profile black

      - name: Run black (format code)
        run: |
          black .

      - name: Check if black made changes and commit if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check for changes
          git diff --exit-code || (
            git config --global user.name "GitHub Actions" &&
            git config --global user.email "actions@github.com" &&
            git add . &&
            git commit -m "Apply black formatting" &&
            git push origin HEAD
          )

  lint:
    runs-on: ubuntu-latest
    needs: format  # The lint job depends on the format job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8 (lint code)
        run: |
          flake8 . --max-line-length=88 --extend-ignore=E203,E701
